{% set version = "1.1.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-predictmeans
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/predictmeans_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/predictmeans/predictmeans_{{ version }}.tar.gz
  sha256: 3d7e3bc839405be2a61767c7d728ca0fba6edd93a88f7ad232a7e04edab83f4e

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-hrw
    - r-mass
    - r-matrix
    - r-car
    - r-ggplot2
    - r-glmmtmb
    - r-lme4
    - r-lmeinfo
    - r-lmesplines
    - r-lmertest
    - r-nlme
    - r-numderiv
    - r-pbkrtest
    - r-plotly
    - r-plyr
    - r-reformulas
    - r-splines2
  run:
    - r-base
    - r-hrw
    - r-mass
    - r-matrix
    - r-car
    - r-ggplot2
    - r-glmmtmb
    - r-lme4
    - r-lmeinfo
    - r-lmesplines
    - r-lmertest
    - r-nlme
    - r-numderiv
    - r-pbkrtest
    - r-plotly
    - r-plyr
    - r-reformulas
    - r-splines2

test:
  commands:
    - $R -e "library('predictmeans')"           # [not win]
    - "\"%R%\" -e \"library('predictmeans')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=predictmeans
  license: GPL-2.0-or-later
  summary: Providing functions to diagnose and make inferences from various linear models, such as those obtained from 'aov', 'lm', 'glm', 'gls', 'lme', and 'lmer'. Inferences include predicted means and standard errors, contrasts, multiple comparisons, permutation tests and graphs.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - brendanf

# Package: predictmeans
# Type: Package
# Title: Calculate Predicted Means for Linear Models
# Version: 1.0.4
# Date: 2020-04-14
# Author: Dongwen Luo, Siva Ganesh and John Koolaard
# Maintainer: Dongwen Luo <dongwen.luo@agresearch.co.nz>
# Description: Providing functions to diagnose and make inferences from various linear models, such as those obtained from 'aov', 'lm', 'glm', 'gls', 'lme', and 'lmer'. Inferences include predicted means and standard errors, contrasts, multiple comparisons, permutation tests and graphs.
# License: GPL (>= 2)
# Depends: R (>= 3.5.0), lme4, nlme, parallel
# Imports: ggplot2, graphics, grDevices, Matrix, methods, numDeriv, pbkrtest, plyr, stats, utils
# URL: https://CRAN.R-project.org/package=predictmeans
# Repository: CRAN
# Date/Publication: 2020-04-15 05:40:03 UTC
# NeedsCompilation: no
# Packaged: 2020-04-14 23:30:17 UTC; LuoD
