{% set version = "1.0.6" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-predictmeans
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/predictmeans_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/predictmeans/predictmeans_{{ version }}.tar.gz
  sha256: b131a637dd5a6972e109011c193c4f752b0564af2d43d3ebd8db515bda3ee3d5

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-matrix
    - r-ggplot2
    - r-lme4
    - r-lmeinfo
    - r-nlme
    - r-pbkrtest
    - r-plyr
  run:
    - r-base
    - r-matrix
    - r-ggplot2
    - r-lme4
    - r-lmeinfo
    - r-nlme
    - r-pbkrtest
    - r-plyr

test:
  commands:
    - $R -e "library('predictmeans')"           # [not win]
    - "\"%R%\" -e \"library('predictmeans')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=predictmeans
  license: GPL-2.0-or-later
  summary: Providing functions to diagnose and make inferences from various linear models, such as those obtained from 'aov', 'lm', 'glm', 'gls', 'lme', and 'lmer'. Inferences include predicted means and standard errors, contrasts, multiple comparisons, permutation tests and graphs.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - brendanf

# Package: predictmeans
# Type: Package
# Title: Calculate Predicted Means for Linear Models
# Version: 1.0.4
# Date: 2020-04-14
# Author: Dongwen Luo, Siva Ganesh and John Koolaard
# Maintainer: Dongwen Luo <dongwen.luo@agresearch.co.nz>
# Description: Providing functions to diagnose and make inferences from various linear models, such as those obtained from 'aov', 'lm', 'glm', 'gls', 'lme', and 'lmer'. Inferences include predicted means and standard errors, contrasts, multiple comparisons, permutation tests and graphs.
# License: GPL (>= 2)
# Depends: R (>= 3.5.0), lme4, nlme, parallel
# Imports: ggplot2, graphics, grDevices, Matrix, methods, numDeriv, pbkrtest, plyr, stats, utils
# URL: https://CRAN.R-project.org/package=predictmeans
# Repository: CRAN
# Date/Publication: 2020-04-15 05:40:03 UTC
# NeedsCompilation: no
# Packaged: 2020-04-14 23:30:17 UTC; LuoD
